-- File: clkDriver.vhd
-- Generated by MyHDL 0.9.0
-- Date: Wed Mar 29 19:40:30 2017


library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_090.all;

entity clkDriver is
    port (
        clk: inout unsigned(7 downto 0)
    );
end entity clkDriver;


architecture MyHDL of clkDriver is






begin





CLKDRIVER_DRIVERCLK: process (<myhdl._delay.delay object at 0x7f42c67ff4d0>) is
begin
    clk <= to_unsigned((not bool(clk)), 8);
end process CLKDRIVER_DRIVERCLK;

end architecture MyHDL;
